callback, payload, results, entry = "feature-callback", "payload", "single_results", "entry"
headword, phonetics, senseFamilies = "headword", "phonetics", "sense_families"
text, oxfordAudio = "text", "oxford_audio"
partsOfSpeech, value, senses = "parts_of_speech", "value", "senses"
definition, examples, exampleGroups, additionalExamples, thesaurusEntries, antonyms, synonyms,nym, nyms = "definition","examples","example_groups","additional_examples","thesaurus_entries","antonyms","synonyms","nym", "nyms"